FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# 构建阶段：用假值让 next build 不报错
ARG DATABASE_URL="postgresql://x:x@localhost:5432/x"
ARG NEXTAUTH_SECRET="x"
ARG NEXTAUTH_URL="http://localhost:3000"
ARG ADMIN_USERNAME="x"
ARG ADMIN_PASSWORD_HASH="x"

ENV DATABASE_URL=${DATABASE_URL}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV ADMIN_USERNAME=${ADMIN_USERNAME}
ENV ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}

RUN npm run build

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "start"]